import { useEffect, useState } from 'react'
import { LANGUAGES, LanguageContext } from './languageContext'

const EN = {
  language: 'Language',
  'nav.trails': 'TRAILS',
  'nav.liveMap': 'LIVE MAP',
  'nav.sos': 'SOS',
  'nav.logout': 'LOGOUT',
  'nav.signin': 'SIGN IN',
  'home.locationShown': 'DEVICE LOCATION IS SHOWN ON THE LIVE MAP',
  'home.headline': 'Know the safe trail before you start.',
  'home.description': 'Search any destination for a walking route from your current GPS fix. Routes are checked against configured hazard zones when available.',
  'home.signedIn': 'SIGNED IN AS',
  'home.digitalId': 'DIGITAL TOURIST ID',
  'home.idAccepted': 'ID NUMBER FORMAT ACCEPTED',
  'home.aadhaarAccepted': 'Aadhaar checksum passed',
  'home.passportAccepted': 'Passport number format passed',
  'home.govNotQueried': 'Government records were not queried',
  'home.exploreMap': 'EXPLORE INTERACTIVE MAP',
  'home.emergencySos': 'EMERGENCY SOS',
  'home.permitProtocol': 'PERMIT PROTOCOL',
  'home.indianCitizen': 'INDIAN CITIZEN',
  'home.foreignNational': 'FOREIGN NATIONAL',
  'home.ilp': 'Inner Line Permit (ILP)',
  'home.ilpText': 'Required for Indian citizens entering Arunachal Pradesh, Nagaland, Mizoram, and parts of Manipur. Obtainable online or at designated entry points.',
  'home.pap': 'Protected Area Permit (PAP)',
  'home.papText': 'Required for all foreign nationals. Must be obtained through an approved travel agency or Indian Embassy.',
  'home.rap': 'Restricted Area Permit (RAP)',
  'home.rapText': 'Required for certain border regions. Apply through the Ministry of Home Affairs.',
  'home.weather': 'WEATHER',
  'home.weatherUnavailable': 'Live weather feed unavailable',
  'home.alerts': 'ALERTS',
  'home.noAdvisories': 'No active advisories',
  'home.planDestination': 'Plan a destination',
  'home.destinationHelp': 'Search a place to calculate a walking route from your current GPS location.',
  'home.destination': 'Type a destination',
  'home.findRoute': 'FIND WALKING ROUTE',
  'home.hazardZones': 'Configured hazard zones',
  'home.openLiveMap': 'OPEN LIVE MAP',
  'home.noZones': 'No configured hazard zones are available. Routes cannot be safety-verified.',
  'assistant.title': 'Forest safety assistant',
  'assistant.tip1': 'Stay on marked trails and never enter restricted zones.',
  'assistant.tip2': 'Keep at least 100 metres from wild animals. Do not feed them.',
  'assistant.tip3': 'If lost, stay where you are and press SOS.',
  'assistant.tip4': 'Carry water, a torch and a charged phone.',
  'assistant.emergencyPhrase': 'EMERGENCY PHRASE — SHOW OR PLAY TO LOCALS / RANGERS',
  'assistant.sos': 'Help! I am lost in the forest. Please send rangers to my location.',
  'assistant.play': 'PLAY',
  'assistant.readAloud': 'Read aloud',
  'login.portal': 'FOREST SAFETY PORTAL',
  'login.tourist': 'TOURIST',
  'login.staff': 'RANGER / ADMIN',
  'login.entryComplete': 'Tourist entry complete',
  'login.welcome': 'Welcome',
  'login.keepId': 'Keep this ID available for Ranger/Admin tracking. Your raw identity number is not shown here.',
  'login.aadhaarNote': 'The number is checked for length and checksum. The app does not contact UIDAI or verify identity against government records.',
  'login.passportNote': 'The app checks the number format only. Passport authenticity is not checked against government records.',
  'login.usernamePlaceholder': 'Username',
  'login.passwordPlaceholder': 'Password',
  'login.iAm': 'I AM',
  'login.indian': 'INDIAN TOURIST',
  'login.foreign': 'FOREIGN TOURIST',
  'login.fullName': 'FULL NAME',
  'login.email': 'EMAIL ID',
  'login.phone': 'PHONE NUMBER',
  'login.aadhaar': 'AADHAAR NUMBER',
  'login.passport': 'PASSPORT NUMBER',
  'login.continue': 'CONTINUE',
  'login.exploreVisitor': 'EXPLORE AS VISITOR',
  'login.username': 'USERNAME',
  'login.password': 'PASSWORD',
  'login.openConsole': 'OPEN CONSOLE',
  'login.signin': 'SIGN IN',
  'login.authorizedOnly': 'AUTHORIZED PERSONNEL ONLY',
  'sos.title': 'EMERGENCY SOS DISPATCH',
  'sos.helplines': '24/7 EMERGENCY HELPLINES',
  'sos.nationalHelpline': 'National Emergency Services',
  'sos.touristHelpline': 'Tourist Emergency Helpline',
  'sos.tamilHelpline': 'Tamil Nadu Forest & Wildlife Helpline',
  'sos.guidance': 'Emergency guidance',
  'sos.send': 'SEND SOS',
  'map.title': 'LIVE SAFETY & NAVIGATION MAP',
  'map.intercept': 'RANGER GPS INTERCEPT RADAR',
  'map.liveDescription': 'LIVE DEVICE GPS · CONFIGURED HAZARD ZONES · OSM ROUTING',
  'map.tracking': 'TRACKING',
  'map.places': 'PLACES:',
  'map.destination': 'DESTINATION',
  'map.typePlace': 'Type a place',
  'map.findRoute': 'FIND ROUTE',
  'map.routing': 'ROUTING…',
  'map.locating': 'LOCATING…',
  'map.myGps': 'MY GPS LOCATION',
  'map.demoZones': 'DEMO PLACES & GEOFENCES',
  'map.basemap': 'BASEMAP:',
  'map.walkingDirections': 'WALKING DIRECTIONS',
  'map.upNext': 'UP NEXT',
  'map.liveGps': 'LIVE GPS',
  'map.searchingGps': 'GPS SEARCHING',
  'map.locationUnavailable': 'DEVICE LOCATION NOT ACQUIRED',
  'map.deadReckoning': 'DEAD RECKONING KINEMATICS RADAR',
  'map.hazardAlert': 'CONFIGURED HAZARD GEOFENCE ALERT',
  'map.acknowledge': 'ACKNOWLEDGE & RETURN TO PATH',
  'map.rangerLog': 'VIEW RANGER LOG',
  'map.basemapTopo': 'Topographic',
  'map.basemapSatellite': 'Satellite',
  'map.basemapOsm': 'Street / OSM',
  'route.drive': 'Drive',
  'route.title': 'NAVIGATION & ROUTING',
  'route.walk': 'Walk',
  'route.cycle': 'Cycle',
  'route.transit': 'Transit',
  'route.startGps': 'Start (blank = my GPS location)',
  'route.addStop': 'ADD STOP',
  'route.removeStop': 'Remove stop',
  'route.voice': 'Voice guidance',
  'route.getDirections': 'GET DIRECTIONS',
  'route.openTransit': 'OPEN TRANSIT ROUTE',
  'route.nextStep': 'NEXT STEP',
  'route.shareLocation': 'SHARE LIVE LOCATION',
  'route.streetView': 'STREET VIEW',
  'route.hazardWarning': 'Route passes through',
  'route.for': 'for',
  'route.metres': 'metres',
  'route.onto': 'onto',
  'route.stop': 'Stop',
  'route.minutes': 'min',
  'route.start': 'Start',
  'route.arrive': 'Arrive',
  'route.turn': 'Turn',
  'route.continue': 'Continue',
  'route.merge': 'Merge',
  'route.enterRoundabout': 'Enter the roundabout',
  'route.exitRoundabout': 'Exit the roundabout',
  'route.left': 'left',
  'route.right': 'right',
  'route.straight': 'straight',
  'route.slightLeft': 'slightly left',
  'route.slightRight': 'slightly right',
  'route.sharpLeft': 'sharp left',
  'route.sharpRight': 'sharp right',
  'route.uturn': 'make a U-turn',
  'voice.title': 'VOICE EMERGENCY MONITOR',
  'voice.enable': 'ENABLE VOICE MONITOR',
  'voice.stop': 'STOP LISTENING',
  'voice.listening': 'LISTENING FOR EMERGENCY PHRASES',
  'voice.spokenLanguage': 'Spoken language',
  'voice.permissionHint': 'Microphone permission is required. Your browser processes speech; listening works only while this page is open.',
  'voice.unsupported': 'Voice emergency detection is not supported by this browser.',
  'voice.permissionDenied': 'Microphone access was denied. Allow microphone access to use voice monitoring.',
  'voice.unavailable': 'Speech recognition is unavailable. Check your connection and try again.',
  'voice.possibleEmergency': 'Possible emergency detected',
  'voice.areYouSafe': 'Are you safe?',
  'voice.imSafe': "I'm Safe",
  'voice.sendSos': 'Send SOS',
  'voice.detectedPhrase': 'Detected phrase',
}

const TRANSLATIONS = {
  en: EN,
  ta: {
    language: 'மொழி',
    'nav.trails': 'பாதைகள்', 'nav.liveMap': 'நேரடி வரைபடம்', 'nav.sos': 'அவசர உதவி', 'nav.logout': 'வெளியேறு', 'nav.signin': 'உள்நுழை',
    'home.locationShown': 'சாதன இருப்பிடம் நேரடி வரைபடத்தில் காட்டப்படும்',
    'home.headline': 'தொடங்குவதற்கு முன் பாதுகாப்பான பாதையை அறியுங்கள்.',
    'home.description': 'தற்போதைய GPS இருப்பிடத்திலிருந்து நடைபாதையைத் தேடுங்கள். அமைக்கப்பட்டுள்ள அபாய மண்டலங்களுடன் பாதைகள் சரிபார்க்கப்படும்.',
    'home.signedIn': 'உள்நுழைந்தவர்', 'home.digitalId': 'டிஜிட்டல் சுற்றுலாப் பயணி அடையாளம்', 'home.idAccepted': 'அடையாள எண் வடிவம் ஏற்கப்பட்டது',
    'home.aadhaarAccepted': 'ஆதார் சரிபார்ப்பு வெற்றியடைந்தது', 'home.passportAccepted': 'கடவுச்சீட்டு எண் வடிவம் சரிபார்க்கப்பட்டது', 'home.govNotQueried': 'அரசுப் பதிவுகள் சரிபார்க்கப்படவில்லை',
    'home.exploreMap': 'ஊடாடும் வரைபடத்தைத் திறக்கவும்', 'home.emergencySos': 'அவசர SOS', 'home.permitProtocol': 'அனுமதி நடைமுறை', 'home.indianCitizen': 'இந்தியக் குடிமகன்', 'home.foreignNational': 'வெளிநாட்டவர்',
    'home.ilp': 'உள் நுழைவு அனுமதி (ILP)', 'home.ilpText': 'அருணாச்சலப் பிரதேசம், நாகாலாந்து, மிசோரம் மற்றும் மணிப்பூரின் சில பகுதிகளுக்குச் செல்லும் இந்தியக் குடிமக்களுக்கு இது தேவை. இணையத்தில் அல்லது நியமிக்கப்பட்ட இடங்களில் பெறலாம்.',
    'home.pap': 'பாதுகாக்கப்பட்ட பகுதி அனுமதி (PAP)', 'home.papText': 'அனைத்து வெளிநாட்டவர்களுக்கும் தேவை. அங்கீகரிக்கப்பட்ட பயண நிறுவனம் அல்லது இந்தியத் தூதரகம் மூலம் பெற வேண்டும்.',
    'home.rap': 'கட்டுப்படுத்தப்பட்ட பகுதி அனுமதி (RAP)', 'home.rapText': 'சில எல்லைப் பகுதிகளுக்குத் தேவை. உள்துறை அமைச்சகத்தில் விண்ணப்பிக்கவும்.',
    'home.weather': 'வானிலை', 'home.weatherUnavailable': 'நேரடி வானிலை தகவல் கிடைக்கவில்லை', 'home.alerts': 'எச்சரிக்கைகள்', 'home.noAdvisories': 'செயலில் உள்ள அறிவிப்புகள் இல்லை',
    'home.planDestination': 'இலக்கைத் திட்டமிடுங்கள்', 'home.destinationHelp': 'தற்போதைய GPS இருப்பிடத்திலிருந்து நடைபாதையைக் கணக்கிட இடத்தைத் தேடுங்கள்.', 'home.destination': 'இலக்கை உள்ளிடுங்கள்', 'home.findRoute': 'நடைபாதையைக் கண்டறியுங்கள்',
    'home.hazardZones': 'அமைக்கப்பட்ட அபாய மண்டலங்கள்', 'home.openLiveMap': 'நேரடி வரைபடத்தைத் திறக்கவும்', 'home.noZones': 'அமைக்கப்பட்ட அபாய மண்டலங்கள் இல்லை. பாதையின் பாதுகாப்பைச் சரிபார்க்க முடியாது.',
    'assistant.title': 'வன பாதுகாப்பு உதவியாளர்', 'assistant.tip1': 'குறிக்கப்பட்ட பாதைகளில் மட்டும் செல்லுங்கள்; தடை செய்யப்பட்ட பகுதிகளுக்குள் நுழைய வேண்டாம்.',
    'assistant.tip2': 'காட்டு விலங்குகளிடமிருந்து குறைந்தது 100 மீட்டர் தூரம் இருங்கள்; உணவளிக்க வேண்டாம்.', 'assistant.tip3': 'வழி தவறினால் இருக்கும் இடத்திலேயே இருந்து SOS அழுத்துங்கள்.', 'assistant.tip4': 'தண்ணீர், டார்ச் மற்றும் சார்ஜ் செய்த போன் வைத்திருங்கள்.',
    'assistant.emergencyPhrase': 'அவசரச் செய்தி — உள்ளூர் மக்களிடம் / வனக் காவலர்களிடம் காட்டவும் அல்லது ஒலிக்கவும்', 'assistant.sos': 'உதவி! நான் காட்டில் வழி தவறிவிட்டேன். என் இடத்திற்கு ரேஞ்சர்களை அனுப்புங்கள்.', 'assistant.play': 'ஒலிக்கவும்', 'assistant.readAloud': 'சத்தமாக வாசிக்கவும்',
    'login.portal': 'வன பாதுகாப்பு தளம்', 'login.tourist': 'சுற்றுலாப் பயணி', 'login.staff': 'வனக் காவலர் / நிர்வாகம்', 'login.iAm': 'நான்', 'login.indian': 'இந்தியச் சுற்றுலாப் பயணி', 'login.foreign': 'வெளிநாட்டுச் சுற்றுலாப் பயணி',
    'login.entryComplete': 'சுற்றுலாப் பயணி பதிவு முடிந்தது', 'login.welcome': 'வரவேற்கிறோம்', 'login.keepId': 'இந்த அடையாள எண்ணை வனக் காவலர் / நிர்வாகக் கண்காணிப்புக்காக வைத்திருங்கள். உங்கள் உண்மையான அடையாள எண் இங்கு காட்டப்படாது.',
    'login.aadhaarNote': 'எண்ணின் நீளம் மற்றும் சரிபார்ப்புக் குறியீடு மட்டுமே சரிபார்க்கப்படும். அரசு பதிவுகள் அணுகப்படுவதில்லை.', 'login.passportNote': 'கடவுச்சீட்டு எண்ணின் வடிவம் மட்டுமே சரிபார்க்கப்படும். அரசு பதிவுகள் அணுகப்படுவதில்லை.', 'login.usernamePlaceholder': 'பயனர் பெயர்', 'login.passwordPlaceholder': 'கடவுச்சொல்',
    'login.fullName': 'முழுப் பெயர்', 'login.email': 'மின்னஞ்சல்', 'login.phone': 'தொலைபேசி எண்', 'login.aadhaar': 'ஆதார் எண்', 'login.passport': 'கடவுச்சீட்டு எண்', 'login.continue': 'தொடரவும்', 'login.exploreVisitor': 'பார்வையாளராகத் தொடரவும்',
    'login.username': 'பயனர் பெயர்', 'login.password': 'கடவுச்சொல்', 'login.openConsole': 'கன்சோலைத் திறக்கவும்', 'login.signin': 'உள்நுழை', 'login.authorizedOnly': 'அங்கீகரிக்கப்பட்ட பணியாளர்கள் மட்டும்',
    'sos.title': 'அவசர SOS அனுப்புதல்', 'sos.helplines': '24/7 அவசர உதவி எண்கள்', 'sos.nationalHelpline': 'தேசிய அவசர சேவை', 'sos.touristHelpline': 'சுற்றுலாப் பயணி அவசர உதவி எண்', 'sos.tamilHelpline': 'தமிழ்நாடு வன மற்றும் வனவிலங்கு உதவி எண்', 'sos.guidance': 'அவசர வழிகாட்டுதல்', 'sos.send': 'SOS அனுப்பவும்',
    'map.title': 'நேரடி பாதுகாப்பு மற்றும் வழிசெலுத்தல் வரைபடம்', 'map.intercept': 'வனக் காவலர் GPS கண்காணிப்பு', 'map.liveDescription': 'நேரடி சாதன GPS · அமைக்கப்பட்ட அபாய மண்டலங்கள் · OSM வழித்தடம்', 'map.tracking': 'கண்காணிப்பு',
    'map.places': 'இடங்கள்:', 'map.destination': 'இலக்கு', 'map.typePlace': 'இடத்தை உள்ளிடுங்கள்', 'map.findRoute': 'பாதையைக் கண்டறியுங்கள்', 'map.routing': 'பாதை கணக்கிடப்படுகிறது…', 'map.locating': 'இடம் கண்டறியப்படுகிறது…', 'map.myGps': 'என் GPS இருப்பிடம்',
    'map.demoZones': 'மாதிரி இடங்கள் மற்றும் எல்லைகள்', 'map.basemap': 'வரைபட வகை:', 'map.walkingDirections': 'நடை வழிகாட்டுதல்', 'map.upNext': 'அடுத்து', 'map.liveGps': 'நேரடி GPS', 'map.searchingGps': 'GPS தேடப்படுகிறது', 'map.locationUnavailable': 'சாதன இருப்பிடம் பெறப்படவில்லை',
    'map.deadReckoning': 'GPS இல்லாதபோது கணிக்கப்பட்ட இடம்', 'map.hazardAlert': 'அமைக்கப்பட்ட அபாய மண்டல எச்சரிக்கை', 'map.acknowledge': 'உறுதிசெய்து பாதைக்குத் திரும்புங்கள்', 'map.rangerLog': 'வனக் காவலர் பதிவைக் காண்க',
    'map.basemapTopo': 'நிலஅமைப்பு', 'map.basemapSatellite': 'செயற்கைக்கோள்', 'map.basemapOsm': 'தெரு / OSM',
    'route.drive': 'கார்', 'route.title': 'வழிசெலுத்தல் மற்றும் பாதை', 'route.walk': 'நடை', 'route.cycle': 'மிதிவண்டி', 'route.transit': 'போக்குவரத்து', 'route.startGps': 'தொடக்கம் (காலியாக விட்டால் என் GPS இருப்பிடம்)',
    'route.addStop': 'நிறுத்தத்தைச் சேர்க்கவும்', 'route.removeStop': 'நிறுத்தத்தை நீக்கவும்', 'route.voice': 'குரல் வழிகாட்டுதல்', 'route.getDirections': 'வழிகாட்டுதலைப் பெறுங்கள்', 'route.openTransit': 'போக்குவரத்து வழியைத் திறக்கவும்',
    'route.nextStep': 'அடுத்த படி', 'route.shareLocation': 'நேரடி இருப்பிடத்தைப் பகிரவும்', 'route.streetView': 'தெருக் காட்சி', 'route.hazardWarning': 'இந்த அபாய மண்டலங்கள் வழியாகச் செல்கிறது', 'route.for': 'தூரம்', 'route.metres': 'மீட்டர்', 'route.onto': '', 'route.stop': 'நிறுத்தம்', 'route.minutes': 'நிமி',
    'route.start': 'தொடங்குங்கள்', 'route.arrive': 'வந்துவிட்டீர்கள்', 'route.turn': 'திரும்பவும்', 'route.continue': 'தொடரவும்', 'route.merge': 'இணையும் பாதையில் தொடரவும்', 'route.enterRoundabout': 'சுற்றுவட்டத்தில் நுழையவும்', 'route.exitRoundabout': 'சுற்றுவட்டத்திலிருந்து வெளியேறவும்',
    'route.left': 'இடப்புறம்', 'route.right': 'வலப்புறம்', 'route.straight': 'நேராக', 'route.slightLeft': 'சிறிது இடப்புறம்', 'route.slightRight': 'சிறிது வலப்புறம்', 'route.sharpLeft': 'கூர்மையாக இடப்புறம்', 'route.sharpRight': 'கூர்மையாக வலப்புறம்', 'route.uturn': 'திரும்பிச் செல்லவும்',
    'voice.title': 'குரல் அவசரக் கண்காணிப்பு', 'voice.enable': 'குரல் கண்காணிப்பைத் தொடங்கவும்', 'voice.stop': 'கேட்பதை நிறுத்தவும்', 'voice.listening': 'அவசரச் சொற்களைக் கேட்கிறது', 'voice.spokenLanguage': 'பேசும் மொழி',
    'voice.permissionHint': 'மைக்ரோஃபோன் அனுமதி தேவை. பேச்சை உங்கள் உலாவி செயலாக்கும்; இந்தப் பக்கம் திறந்திருக்கும் போது மட்டுமே கேட்கும்.', 'voice.unsupported': 'இந்த உலாவியில் குரல் அவசரக் கண்டறிதல் ஆதரிக்கப்படவில்லை.',
    'voice.permissionDenied': 'மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது. குரல் கண்காணிப்பைப் பயன்படுத்த அனுமதியை வழங்கவும்.', 'voice.unavailable': 'குரல் அறிதல் கிடைக்கவில்லை. இணைய இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    'voice.possibleEmergency': 'சாத்தியமான அவசரநிலை கண்டறியப்பட்டது', 'voice.areYouSafe': 'நீங்கள் பாதுகாப்பாக இருக்கிறீர்களா?', 'voice.imSafe': 'நான் பாதுகாப்பாக இருக்கிறேன்', 'voice.sendSos': 'SOS அனுப்பவும்', 'voice.detectedPhrase': 'கண்டறியப்பட்ட சொல்',
  },
  hi: {
    language: 'भाषा',
    'nav.trails': 'रास्ते', 'nav.liveMap': 'लाइव नक्शा', 'nav.sos': 'SOS', 'nav.logout': 'लॉग आउट', 'nav.signin': 'साइन इन',
    'home.locationShown': 'डिवाइस की लोकेशन लाइव नक्शे पर दिखाई जाती है',
    'home.headline': 'शुरू करने से पहले सुरक्षित रास्ता जानें।',
    'home.description': 'अपने मौजूदा GPS स्थान से पैदल रास्ता खोजें। उपलब्ध होने पर रास्तों की जाँच तय किए गए खतरे वाले क्षेत्रों से की जाती है।',
    'home.signedIn': 'साइन इन किया है', 'home.digitalId': 'डिजिटल पर्यटक पहचान', 'home.idAccepted': 'पहचान संख्या का प्रारूप स्वीकार किया गया',
    'home.aadhaarAccepted': 'आधार चेकसम सही है', 'home.passportAccepted': 'पासपोर्ट संख्या का प्रारूप सही है', 'home.govNotQueried': 'सरकारी रिकॉर्ड की जाँच नहीं की गई',
    'home.exploreMap': 'इंटरैक्टिव नक्शा खोलें', 'home.emergencySos': 'आपातकालीन SOS', 'home.permitProtocol': 'परमिट प्रक्रिया', 'home.indianCitizen': 'भारतीय नागरिक', 'home.foreignNational': 'विदेशी नागरिक',
    'home.ilp': 'इनर लाइन परमिट (ILP)', 'home.ilpText': 'अरुणाचल प्रदेश, नागालैंड, मिजोरम और मणिपुर के कुछ हिस्सों में जाने वाले भारतीय नागरिकों के लिए आवश्यक। इसे ऑनलाइन या निर्धारित प्रवेश केंद्रों से प्राप्त करें।',
    'home.pap': 'संरक्षित क्षेत्र परमिट (PAP)', 'home.papText': 'सभी विदेशी नागरिकों के लिए आवश्यक। इसे स्वीकृत ट्रैवल एजेंसी या भारतीय दूतावास के माध्यम से प्राप्त करें।',
    'home.rap': 'प्रतिबंधित क्षेत्र परमिट (RAP)', 'home.rapText': 'कुछ सीमावर्ती क्षेत्रों के लिए आवश्यक। गृह मंत्रालय में आवेदन करें।',
    'home.weather': 'मौसम', 'home.weatherUnavailable': 'लाइव मौसम जानकारी उपलब्ध नहीं है', 'home.alerts': 'चेतावनी', 'home.noAdvisories': 'कोई सक्रिय सूचना नहीं',
    'home.planDestination': 'गंतव्य की योजना बनाएँ', 'home.destinationHelp': 'अपने वर्तमान GPS स्थान से पैदल रास्ता खोजने के लिए जगह खोजें।', 'home.destination': 'गंतव्य लिखें', 'home.findRoute': 'पैदल रास्ता खोजें',
    'home.hazardZones': 'निर्धारित खतरे वाले क्षेत्र', 'home.openLiveMap': 'लाइव नक्शा खोलें', 'home.noZones': 'कोई खतरे वाला क्षेत्र निर्धारित नहीं है। रास्ते की सुरक्षा की पुष्टि नहीं हो सकती।',
    'assistant.title': 'वन सुरक्षा सहायक', 'assistant.tip1': 'चिह्नित रास्तों पर ही चलें, प्रतिबंधित क्षेत्र में न जाएँ।', 'assistant.tip2': 'जंगली जानवरों से कम से कम 100 मीटर दूर रहें और उन्हें खाना न दें।',
    'assistant.tip3': 'रास्ता भटक जाएँ तो वहीं रुकें और SOS दबाएँ।', 'assistant.tip4': 'पानी, टॉर्च और चार्ज किया हुआ फ़ोन साथ रखें।', 'assistant.emergencyPhrase': 'आपातकालीन संदेश — स्थानीय लोगों / रेंजरों को दिखाएँ या सुनाएँ', 'assistant.sos': 'बचाओ! मैं जंगल में खो गया हूँ। कृपया रेंजर मेरी लोकेशन पर भेजें।', 'assistant.play': 'चलाएँ', 'assistant.readAloud': 'ज़ोर से पढ़ें',
    'login.portal': 'वन सुरक्षा पोर्टल', 'login.tourist': 'पर्यटक', 'login.staff': 'रेंजर / एडमिन', 'login.iAm': 'मैं हूँ', 'login.indian': 'भारतीय पर्यटक', 'login.foreign': 'विदेशी पर्यटक',
    'login.entryComplete': 'पर्यटक प्रवेश पूरा हुआ', 'login.welcome': 'स्वागत है', 'login.keepId': 'रेंजर/एडमिन ट्रैकिंग के लिए यह ID संभालकर रखें। आपका असली पहचान नंबर यहाँ नहीं दिखाया जाता।',
    'login.aadhaarNote': 'नंबर की लंबाई और चेकसम की जाँच होती है। सरकारी रिकॉर्ड से संपर्क नहीं किया जाता।', 'login.passportNote': 'केवल पासपोर्ट नंबर के प्रारूप की जाँच होती है। सरकारी रिकॉर्ड से संपर्क नहीं किया जाता।', 'login.usernamePlaceholder': 'यूज़रनेम', 'login.passwordPlaceholder': 'पासवर्ड',
    'login.fullName': 'पूरा नाम', 'login.email': 'ईमेल', 'login.phone': 'फ़ोन नंबर', 'login.aadhaar': 'आधार नंबर', 'login.passport': 'पासपोर्ट नंबर', 'login.continue': 'आगे बढ़ें', 'login.exploreVisitor': 'बिना साइन इन देखें',
    'login.username': 'यूज़रनेम', 'login.password': 'पासवर्ड', 'login.openConsole': 'कंसोल खोलें', 'login.signin': 'साइन इन', 'login.authorizedOnly': 'केवल अधिकृत कर्मचारी',
    'sos.title': 'आपातकालीन SOS भेजें', 'sos.helplines': '24/7 आपातकालीन हेल्पलाइन', 'sos.nationalHelpline': 'राष्ट्रीय आपातकालीन सेवा', 'sos.touristHelpline': 'पर्यटक आपातकालीन हेल्पलाइन', 'sos.tamilHelpline': 'तमिलनाडु वन एवं वन्यजीव हेल्पलाइन', 'sos.guidance': 'आपातकालीन निर्देश', 'sos.send': 'SOS भेजें',
    'map.title': 'लाइव सुरक्षा और नेविगेशन नक्शा', 'map.intercept': 'रेंजर GPS ट्रैकिंग', 'map.liveDescription': 'लाइव डिवाइस GPS · निर्धारित खतरे वाले क्षेत्र · OSM मार्ग', 'map.tracking': 'ट्रैकिंग',
    'map.places': 'स्थान:', 'map.destination': 'गंतव्य', 'map.typePlace': 'जगह लिखें', 'map.findRoute': 'रास्ता खोजें', 'map.routing': 'रास्ता बनाया जा रहा है…', 'map.locating': 'लोकेशन खोजी जा रही है…', 'map.myGps': 'मेरी GPS लोकेशन',
    'map.demoZones': 'डेमो स्थान और क्षेत्र', 'map.basemap': 'नक्शे का प्रकार:', 'map.walkingDirections': 'पैदल दिशा-निर्देश', 'map.upNext': 'आगे', 'map.liveGps': 'लाइव GPS', 'map.searchingGps': 'GPS खोज जारी', 'map.locationUnavailable': 'डिवाइस की लोकेशन नहीं मिली',
    'map.deadReckoning': 'GPS के बिना अनुमानित लोकेशन', 'map.hazardAlert': 'निर्धारित खतरे वाले क्षेत्र की चेतावनी', 'map.acknowledge': 'स्वीकार करें और रास्ते पर लौटें', 'map.rangerLog': 'रेंजर लॉग देखें',
    'map.basemapTopo': 'स्थलाकृतिक', 'map.basemapSatellite': 'सैटेलाइट', 'map.basemapOsm': 'सड़क / OSM',
    'route.drive': 'ड्राइव', 'route.title': 'नेविगेशन और रास्ता', 'route.walk': 'पैदल', 'route.cycle': 'साइकिल', 'route.transit': 'ट्रांज़िट', 'route.startGps': 'शुरुआत (खाली छोड़ें = मेरी GPS लोकेशन)',
    'route.addStop': 'स्टॉप जोड़ें', 'route.removeStop': 'स्टॉप हटाएँ', 'route.voice': 'आवाज़ से दिशा-निर्देश', 'route.getDirections': 'दिशा-निर्देश पाएँ', 'route.openTransit': 'ट्रांज़िट रास्ता खोलें',
    'route.nextStep': 'अगला मोड़', 'route.shareLocation': 'लाइव लोकेशन साझा करें', 'route.streetView': 'स्ट्रीट व्यू', 'route.hazardWarning': 'रास्ता इन खतरे वाले क्षेत्रों से गुजरता है', 'route.for': 'दूरी', 'route.metres': 'मीटर', 'route.onto': 'पर', 'route.stop': 'स्टॉप', 'route.minutes': 'मिनट',
    'route.start': 'शुरू करें', 'route.arrive': 'पहुँच गए', 'route.turn': 'मुड़ें', 'route.continue': 'जारी रखें', 'route.merge': 'मिलती सड़क पर आगे बढ़ें', 'route.enterRoundabout': 'गोल चक्कर में प्रवेश करें', 'route.exitRoundabout': 'गोल चक्कर से बाहर निकलें',
    'route.left': 'बाएँ', 'route.right': 'दाएँ', 'route.straight': 'सीधे', 'route.slightLeft': 'हल्का बाएँ', 'route.slightRight': 'हल्का दाएँ', 'route.sharpLeft': 'तेज़ बाएँ', 'route.sharpRight': 'तेज़ दाएँ', 'route.uturn': 'यू-टर्न लें',
    'voice.title': 'आवाज़ से आपातकालीन निगरानी', 'voice.enable': 'आवाज़ निगरानी शुरू करें', 'voice.stop': 'सुनना बंद करें', 'voice.listening': 'आपातकालीन शब्द सुने जा रहे हैं', 'voice.spokenLanguage': 'बोली जाने वाली भाषा',
    'voice.permissionHint': 'माइक्रोफ़ोन की अनुमति ज़रूरी है। बोली को आपका ब्राउज़र प्रोसेस करता है; सुनना केवल इस पेज के खुले रहने पर काम करता है।', 'voice.unsupported': 'यह ब्राउज़र आवाज़ से आपातकाल पहचानने की सुविधा नहीं देता।',
    'voice.permissionDenied': 'माइक्रोफ़ोन की अनुमति नहीं मिली। आवाज़ निगरानी के लिए माइक्रोफ़ोन की अनुमति दें।', 'voice.unavailable': 'वाक् पहचान उपलब्ध नहीं है। कनेक्शन जाँचकर फिर कोशिश करें।',
    'voice.possibleEmergency': 'संभावित आपातकाल का पता चला', 'voice.areYouSafe': 'क्या आप सुरक्षित हैं?', 'voice.imSafe': 'मैं सुरक्षित हूँ', 'voice.sendSos': 'SOS भेजें', 'voice.detectedPhrase': 'पहचाना गया शब्द',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      const saved = localStorage.getItem('vr_language')
      return TRANSLATIONS[saved] ? saved : 'en'
    } catch {
      return 'en'
    }
  })

  useEffect(() => {
    const selected = LANGUAGES.find(item => item.code === language) || LANGUAGES[0]
    document.documentElement.lang = selected.locale
    try {
      localStorage.setItem('vr_language', language)
    } catch {
      // Keep the selected language for this page even when storage is unavailable.
    }
  }, [language])

  const selectLanguage = code => {
    if (!TRANSLATIONS[code]) return
    try {
      localStorage.setItem('vr_language', code)
    } catch {
      // The in-memory selection still applies when storage is unavailable.
    }
    setLanguage(code)
  }

  const value = {
    language,
    setLanguage: selectLanguage,
    locale: LANGUAGES.find(item => item.code === language)?.locale || 'en-IN',
    t: key => TRANSLATIONS[language]?.[key] || EN[key] || key,
  }

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}
